# Generated by Django 4.1.4 on 2023-01-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('thumbnail', models.ImageField(upload_to='course/thumbnail', verbose_name='عکس زمینه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('completed', models.BooleanField(default=False, verbose_name='به اتمام رسیده/درحال برگزاری')),
                ('free', models.BooleanField(default=True, verbose_name='رایگان/غیررایگان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('price', models.IntegerField(verbose_name='هزینه')),
                ('content', tinymce.models.HTMLField(verbose_name='محتوا')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='category.child', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reply', to='course.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_reply', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(max_length=255, verbose_name='آدرس')),
                ('part', models.IntegerField(verbose_name='قسمت')),
                ('free', models.BooleanField(default=False, verbose_name='رایگان/غیررایگان')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='course.course', verbose_name='دوره')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comment', to='course.course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
