# Generated by Django 4.1.4 on 2023-01-05 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'Parent Category',
                'verbose_name_plural': 'Parent Categories',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='category.parent')),
            ],
            options={
                'verbose_name': 'Child Category',
                'verbose_name_plural': 'Child Categories',
            },
        ),
    ]
